#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PO_Search
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="EIWarehouse")]
	public partial class POClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPOHeader(POHeader instance);
    partial void UpdatePOHeader(POHeader instance);
    partial void DeletePOHeader(POHeader instance);
    partial void InsertPOLine(POLine instance);
    partial void UpdatePOLine(POLine instance);
    partial void DeletePOLine(POLine instance);
    #endregion
		
		public POClassesDataContext() : 
				base(global::PO_Search.Properties.Settings.Default.EIWarehouseConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public POClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public POClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public POClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public POClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<POHeader> POHeaders
		{
			get
			{
				return this.GetTable<POHeader>();
			}
		}
		
		public System.Data.Linq.Table<POLine> POLines
		{
			get
			{
				return this.GetTable<POLine>();
			}
		}
		
		public System.Data.Linq.Table<employee> employees
		{
			get
			{
				return this.GetTable<employee>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.POHeader")]
	public partial class POHeader : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Company;
		
		private long _PoNum;
		
		private System.Nullable<System.DateTime> _OrderDate;
		
		private System.Nullable<bool> _IsAnRFQ;
		
		private System.Nullable<int> _BuyerID;
		
		private string _BuyerPhone;
		
		private string _BuyerFax;
		
		private string _BuyerName;
		
		private System.Nullable<bool> _BuyerIsAnEmpOfCurrCompany;
		
		private string _EpicorCurrencyCode;
		
		private string _CurrencyTickerSymbol;
		
		private System.Nullable<decimal> _POExchangeRate;
		
		private string _ShipVia;
		
		private string _ShipToName;
		
		private string _ShipToAdd1;
		
		private string _ShipToAdd2;
		
		private string _ShipToAdd3;
		
		private string _ShipToCity;
		
		private string _ShipToState;
		
		private string _ShipToZip;
		
		private string _ShipToCountry;
		
		private string _PoCommentText;
		
		private string _VendorPurPoint;
		
		private string _VendorName;
		
		private System.Nullable<long> _VendorNum;
		
		private string _VendAddr1;
		
		private string _VendAddr2;
		
		private string _VendAddr3;
		
		private string _VendCity;
		
		private string _VendState;
		
		private string _VendZip;
		
		private string _VendCountry;
		
		private string _VendPhone;
		
		private string _VendFax;
		
		private string _VendAcct;
		
		private string _VendContact;
		
		private System.Nullable<bool> _VendCntInactive;
		
		private string _VendorRating;
		
		private string _CompName;
		
		private string _CompAddress1;
		
		private string _CompAddress2;
		
		private string _CompAddress3;
		
		private string _CompCity;
		
		private string _CompState;
		
		private string _CompZip;
		
		private string _CompCountry;
		
		private string _CompPhone;
		
		private string _CompFax;
		
		private System.Nullable<bool> _ShowSalesTax;
		
		private System.Nullable<decimal> _SalesTaxPercentageRate;
		
		private string _TaxVerbage;
		
		private System.Nullable<bool> _UseUSADateFormat;
		
		private string _DisplayPoOrderDateText;
		
		private string _DisplayPoNumber;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCompanyChanging(string value);
    partial void OnCompanyChanged();
    partial void OnPoNumChanging(long value);
    partial void OnPoNumChanged();
    partial void OnOrderDateChanging(System.Nullable<System.DateTime> value);
    partial void OnOrderDateChanged();
    partial void OnIsAnRFQChanging(System.Nullable<bool> value);
    partial void OnIsAnRFQChanged();
    partial void OnBuyerIDChanging(System.Nullable<int> value);
    partial void OnBuyerIDChanged();
    partial void OnBuyerPhoneChanging(string value);
    partial void OnBuyerPhoneChanged();
    partial void OnBuyerFaxChanging(string value);
    partial void OnBuyerFaxChanged();
    partial void OnBuyerNameChanging(string value);
    partial void OnBuyerNameChanged();
    partial void OnBuyerIsAnEmpOfCurrCompanyChanging(System.Nullable<bool> value);
    partial void OnBuyerIsAnEmpOfCurrCompanyChanged();
    partial void OnEpicorCurrencyCodeChanging(string value);
    partial void OnEpicorCurrencyCodeChanged();
    partial void OnCurrencyTickerSymbolChanging(string value);
    partial void OnCurrencyTickerSymbolChanged();
    partial void OnPOExchangeRateChanging(System.Nullable<decimal> value);
    partial void OnPOExchangeRateChanged();
    partial void OnShipViaChanging(string value);
    partial void OnShipViaChanged();
    partial void OnShipToNameChanging(string value);
    partial void OnShipToNameChanged();
    partial void OnShipToAdd1Changing(string value);
    partial void OnShipToAdd1Changed();
    partial void OnShipToAdd2Changing(string value);
    partial void OnShipToAdd2Changed();
    partial void OnShipToAdd3Changing(string value);
    partial void OnShipToAdd3Changed();
    partial void OnShipToCityChanging(string value);
    partial void OnShipToCityChanged();
    partial void OnShipToStateChanging(string value);
    partial void OnShipToStateChanged();
    partial void OnShipToZipChanging(string value);
    partial void OnShipToZipChanged();
    partial void OnShipToCountryChanging(string value);
    partial void OnShipToCountryChanged();
    partial void OnPoCommentTextChanging(string value);
    partial void OnPoCommentTextChanged();
    partial void OnVendorPurPointChanging(string value);
    partial void OnVendorPurPointChanged();
    partial void OnVendorNameChanging(string value);
    partial void OnVendorNameChanged();
    partial void OnVendorNumChanging(System.Nullable<long> value);
    partial void OnVendorNumChanged();
    partial void OnVendAddr1Changing(string value);
    partial void OnVendAddr1Changed();
    partial void OnVendAddr2Changing(string value);
    partial void OnVendAddr2Changed();
    partial void OnVendAddr3Changing(string value);
    partial void OnVendAddr3Changed();
    partial void OnVendCityChanging(string value);
    partial void OnVendCityChanged();
    partial void OnVendStateChanging(string value);
    partial void OnVendStateChanged();
    partial void OnVendZipChanging(string value);
    partial void OnVendZipChanged();
    partial void OnVendCountryChanging(string value);
    partial void OnVendCountryChanged();
    partial void OnVendPhoneChanging(string value);
    partial void OnVendPhoneChanged();
    partial void OnVendFaxChanging(string value);
    partial void OnVendFaxChanged();
    partial void OnVendAcctChanging(string value);
    partial void OnVendAcctChanged();
    partial void OnVendContactChanging(string value);
    partial void OnVendContactChanged();
    partial void OnVendCntInactiveChanging(System.Nullable<bool> value);
    partial void OnVendCntInactiveChanged();
    partial void OnVendorRatingChanging(string value);
    partial void OnVendorRatingChanged();
    partial void OnCompNameChanging(string value);
    partial void OnCompNameChanged();
    partial void OnCompAddress1Changing(string value);
    partial void OnCompAddress1Changed();
    partial void OnCompAddress2Changing(string value);
    partial void OnCompAddress2Changed();
    partial void OnCompAddress3Changing(string value);
    partial void OnCompAddress3Changed();
    partial void OnCompCityChanging(string value);
    partial void OnCompCityChanged();
    partial void OnCompStateChanging(string value);
    partial void OnCompStateChanged();
    partial void OnCompZipChanging(string value);
    partial void OnCompZipChanged();
    partial void OnCompCountryChanging(string value);
    partial void OnCompCountryChanged();
    partial void OnCompPhoneChanging(string value);
    partial void OnCompPhoneChanged();
    partial void OnCompFaxChanging(string value);
    partial void OnCompFaxChanged();
    partial void OnShowSalesTaxChanging(System.Nullable<bool> value);
    partial void OnShowSalesTaxChanged();
    partial void OnSalesTaxPercentageRateChanging(System.Nullable<decimal> value);
    partial void OnSalesTaxPercentageRateChanged();
    partial void OnTaxVerbageChanging(string value);
    partial void OnTaxVerbageChanged();
    partial void OnUseUSADateFormatChanging(System.Nullable<bool> value);
    partial void OnUseUSADateFormatChanged();
    partial void OnDisplayPoOrderDateTextChanging(string value);
    partial void OnDisplayPoOrderDateTextChanged();
    partial void OnDisplayPoNumberChanging(string value);
    partial void OnDisplayPoNumberChanged();
    #endregion
		
		public POHeader()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Company", DbType="VarChar(4)")]
		public string Company
		{
			get
			{
				return this._Company;
			}
			set
			{
				if ((this._Company != value))
				{
					this.OnCompanyChanging(value);
					this.SendPropertyChanging();
					this._Company = value;
					this.SendPropertyChanged("Company");
					this.OnCompanyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PoNum", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long PoNum
		{
			get
			{
				return this._PoNum;
			}
			set
			{
				if ((this._PoNum != value))
				{
					this.OnPoNumChanging(value);
					this.SendPropertyChanging();
					this._PoNum = value;
					this.SendPropertyChanged("PoNum");
					this.OnPoNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderDate", DbType="Date")]
		public System.Nullable<System.DateTime> OrderDate
		{
			get
			{
				return this._OrderDate;
			}
			set
			{
				if ((this._OrderDate != value))
				{
					this.OnOrderDateChanging(value);
					this.SendPropertyChanging();
					this._OrderDate = value;
					this.SendPropertyChanged("OrderDate");
					this.OnOrderDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAnRFQ", DbType="Bit")]
		public System.Nullable<bool> IsAnRFQ
		{
			get
			{
				return this._IsAnRFQ;
			}
			set
			{
				if ((this._IsAnRFQ != value))
				{
					this.OnIsAnRFQChanging(value);
					this.SendPropertyChanging();
					this._IsAnRFQ = value;
					this.SendPropertyChanged("IsAnRFQ");
					this.OnIsAnRFQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BuyerID", DbType="Int")]
		public System.Nullable<int> BuyerID
		{
			get
			{
				return this._BuyerID;
			}
			set
			{
				if ((this._BuyerID != value))
				{
					this.OnBuyerIDChanging(value);
					this.SendPropertyChanging();
					this._BuyerID = value;
					this.SendPropertyChanged("BuyerID");
					this.OnBuyerIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BuyerPhone", DbType="VarChar(50)")]
		public string BuyerPhone
		{
			get
			{
				return this._BuyerPhone;
			}
			set
			{
				if ((this._BuyerPhone != value))
				{
					this.OnBuyerPhoneChanging(value);
					this.SendPropertyChanging();
					this._BuyerPhone = value;
					this.SendPropertyChanged("BuyerPhone");
					this.OnBuyerPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BuyerFax", DbType="VarChar(50)")]
		public string BuyerFax
		{
			get
			{
				return this._BuyerFax;
			}
			set
			{
				if ((this._BuyerFax != value))
				{
					this.OnBuyerFaxChanging(value);
					this.SendPropertyChanging();
					this._BuyerFax = value;
					this.SendPropertyChanged("BuyerFax");
					this.OnBuyerFaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BuyerName", DbType="VarChar(50)")]
		public string BuyerName
		{
			get
			{
				return this._BuyerName;
			}
			set
			{
				if ((this._BuyerName != value))
				{
					this.OnBuyerNameChanging(value);
					this.SendPropertyChanging();
					this._BuyerName = value;
					this.SendPropertyChanged("BuyerName");
					this.OnBuyerNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BuyerIsAnEmpOfCurrCompany", DbType="Bit")]
		public System.Nullable<bool> BuyerIsAnEmpOfCurrCompany
		{
			get
			{
				return this._BuyerIsAnEmpOfCurrCompany;
			}
			set
			{
				if ((this._BuyerIsAnEmpOfCurrCompany != value))
				{
					this.OnBuyerIsAnEmpOfCurrCompanyChanging(value);
					this.SendPropertyChanging();
					this._BuyerIsAnEmpOfCurrCompany = value;
					this.SendPropertyChanged("BuyerIsAnEmpOfCurrCompany");
					this.OnBuyerIsAnEmpOfCurrCompanyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EpicorCurrencyCode", DbType="VarChar(4)")]
		public string EpicorCurrencyCode
		{
			get
			{
				return this._EpicorCurrencyCode;
			}
			set
			{
				if ((this._EpicorCurrencyCode != value))
				{
					this.OnEpicorCurrencyCodeChanging(value);
					this.SendPropertyChanging();
					this._EpicorCurrencyCode = value;
					this.SendPropertyChanged("EpicorCurrencyCode");
					this.OnEpicorCurrencyCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrencyTickerSymbol", DbType="VarChar(4)")]
		public string CurrencyTickerSymbol
		{
			get
			{
				return this._CurrencyTickerSymbol;
			}
			set
			{
				if ((this._CurrencyTickerSymbol != value))
				{
					this.OnCurrencyTickerSymbolChanging(value);
					this.SendPropertyChanging();
					this._CurrencyTickerSymbol = value;
					this.SendPropertyChanged("CurrencyTickerSymbol");
					this.OnCurrencyTickerSymbolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POExchangeRate", DbType="Decimal(18,4)")]
		public System.Nullable<decimal> POExchangeRate
		{
			get
			{
				return this._POExchangeRate;
			}
			set
			{
				if ((this._POExchangeRate != value))
				{
					this.OnPOExchangeRateChanging(value);
					this.SendPropertyChanging();
					this._POExchangeRate = value;
					this.SendPropertyChanged("POExchangeRate");
					this.OnPOExchangeRateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipVia", DbType="VarChar(16)")]
		public string ShipVia
		{
			get
			{
				return this._ShipVia;
			}
			set
			{
				if ((this._ShipVia != value))
				{
					this.OnShipViaChanging(value);
					this.SendPropertyChanging();
					this._ShipVia = value;
					this.SendPropertyChanged("ShipVia");
					this.OnShipViaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipToName", DbType="VarChar(50)")]
		public string ShipToName
		{
			get
			{
				return this._ShipToName;
			}
			set
			{
				if ((this._ShipToName != value))
				{
					this.OnShipToNameChanging(value);
					this.SendPropertyChanging();
					this._ShipToName = value;
					this.SendPropertyChanged("ShipToName");
					this.OnShipToNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipToAdd1", DbType="VarChar(120)")]
		public string ShipToAdd1
		{
			get
			{
				return this._ShipToAdd1;
			}
			set
			{
				if ((this._ShipToAdd1 != value))
				{
					this.OnShipToAdd1Changing(value);
					this.SendPropertyChanging();
					this._ShipToAdd1 = value;
					this.SendPropertyChanged("ShipToAdd1");
					this.OnShipToAdd1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipToAdd2", DbType="VarChar(120)")]
		public string ShipToAdd2
		{
			get
			{
				return this._ShipToAdd2;
			}
			set
			{
				if ((this._ShipToAdd2 != value))
				{
					this.OnShipToAdd2Changing(value);
					this.SendPropertyChanging();
					this._ShipToAdd2 = value;
					this.SendPropertyChanged("ShipToAdd2");
					this.OnShipToAdd2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipToAdd3", DbType="VarChar(120)")]
		public string ShipToAdd3
		{
			get
			{
				return this._ShipToAdd3;
			}
			set
			{
				if ((this._ShipToAdd3 != value))
				{
					this.OnShipToAdd3Changing(value);
					this.SendPropertyChanging();
					this._ShipToAdd3 = value;
					this.SendPropertyChanged("ShipToAdd3");
					this.OnShipToAdd3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipToCity", DbType="VarChar(100)")]
		public string ShipToCity
		{
			get
			{
				return this._ShipToCity;
			}
			set
			{
				if ((this._ShipToCity != value))
				{
					this.OnShipToCityChanging(value);
					this.SendPropertyChanging();
					this._ShipToCity = value;
					this.SendPropertyChanged("ShipToCity");
					this.OnShipToCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipToState", DbType="VarChar(32)")]
		public string ShipToState
		{
			get
			{
				return this._ShipToState;
			}
			set
			{
				if ((this._ShipToState != value))
				{
					this.OnShipToStateChanging(value);
					this.SendPropertyChanging();
					this._ShipToState = value;
					this.SendPropertyChanged("ShipToState");
					this.OnShipToStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipToZip", DbType="VarChar(16)")]
		public string ShipToZip
		{
			get
			{
				return this._ShipToZip;
			}
			set
			{
				if ((this._ShipToZip != value))
				{
					this.OnShipToZipChanging(value);
					this.SendPropertyChanging();
					this._ShipToZip = value;
					this.SendPropertyChanged("ShipToZip");
					this.OnShipToZipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipToCountry", DbType="VarChar(20)")]
		public string ShipToCountry
		{
			get
			{
				return this._ShipToCountry;
			}
			set
			{
				if ((this._ShipToCountry != value))
				{
					this.OnShipToCountryChanging(value);
					this.SendPropertyChanging();
					this._ShipToCountry = value;
					this.SendPropertyChanged("ShipToCountry");
					this.OnShipToCountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PoCommentText", DbType="VarChar(1500)")]
		public string PoCommentText
		{
			get
			{
				return this._PoCommentText;
			}
			set
			{
				if ((this._PoCommentText != value))
				{
					this.OnPoCommentTextChanging(value);
					this.SendPropertyChanging();
					this._PoCommentText = value;
					this.SendPropertyChanged("PoCommentText");
					this.OnPoCommentTextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendorPurPoint", DbType="VarChar(4)")]
		public string VendorPurPoint
		{
			get
			{
				return this._VendorPurPoint;
			}
			set
			{
				if ((this._VendorPurPoint != value))
				{
					this.OnVendorPurPointChanging(value);
					this.SendPropertyChanging();
					this._VendorPurPoint = value;
					this.SendPropertyChanged("VendorPurPoint");
					this.OnVendorPurPointChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendorName", DbType="VarChar(120)")]
		public string VendorName
		{
			get
			{
				return this._VendorName;
			}
			set
			{
				if ((this._VendorName != value))
				{
					this.OnVendorNameChanging(value);
					this.SendPropertyChanging();
					this._VendorName = value;
					this.SendPropertyChanged("VendorName");
					this.OnVendorNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendorNum", DbType="BigInt")]
		public System.Nullable<long> VendorNum
		{
			get
			{
				return this._VendorNum;
			}
			set
			{
				if ((this._VendorNum != value))
				{
					this.OnVendorNumChanging(value);
					this.SendPropertyChanging();
					this._VendorNum = value;
					this.SendPropertyChanged("VendorNum");
					this.OnVendorNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendAddr1", DbType="VarChar(120)")]
		public string VendAddr1
		{
			get
			{
				return this._VendAddr1;
			}
			set
			{
				if ((this._VendAddr1 != value))
				{
					this.OnVendAddr1Changing(value);
					this.SendPropertyChanging();
					this._VendAddr1 = value;
					this.SendPropertyChanged("VendAddr1");
					this.OnVendAddr1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendAddr2", DbType="VarChar(120)")]
		public string VendAddr2
		{
			get
			{
				return this._VendAddr2;
			}
			set
			{
				if ((this._VendAddr2 != value))
				{
					this.OnVendAddr2Changing(value);
					this.SendPropertyChanging();
					this._VendAddr2 = value;
					this.SendPropertyChanged("VendAddr2");
					this.OnVendAddr2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendAddr3", DbType="VarChar(120)")]
		public string VendAddr3
		{
			get
			{
				return this._VendAddr3;
			}
			set
			{
				if ((this._VendAddr3 != value))
				{
					this.OnVendAddr3Changing(value);
					this.SendPropertyChanging();
					this._VendAddr3 = value;
					this.SendPropertyChanged("VendAddr3");
					this.OnVendAddr3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendCity", DbType="VarChar(100)")]
		public string VendCity
		{
			get
			{
				return this._VendCity;
			}
			set
			{
				if ((this._VendCity != value))
				{
					this.OnVendCityChanging(value);
					this.SendPropertyChanging();
					this._VendCity = value;
					this.SendPropertyChanged("VendCity");
					this.OnVendCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendState", DbType="VarChar(32)")]
		public string VendState
		{
			get
			{
				return this._VendState;
			}
			set
			{
				if ((this._VendState != value))
				{
					this.OnVendStateChanging(value);
					this.SendPropertyChanging();
					this._VendState = value;
					this.SendPropertyChanged("VendState");
					this.OnVendStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendZip", DbType="VarChar(16)")]
		public string VendZip
		{
			get
			{
				return this._VendZip;
			}
			set
			{
				if ((this._VendZip != value))
				{
					this.OnVendZipChanging(value);
					this.SendPropertyChanging();
					this._VendZip = value;
					this.SendPropertyChanged("VendZip");
					this.OnVendZipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendCountry", DbType="VarChar(20)")]
		public string VendCountry
		{
			get
			{
				return this._VendCountry;
			}
			set
			{
				if ((this._VendCountry != value))
				{
					this.OnVendCountryChanging(value);
					this.SendPropertyChanging();
					this._VendCountry = value;
					this.SendPropertyChanged("VendCountry");
					this.OnVendCountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendPhone", DbType="VarChar(50)")]
		public string VendPhone
		{
			get
			{
				return this._VendPhone;
			}
			set
			{
				if ((this._VendPhone != value))
				{
					this.OnVendPhoneChanging(value);
					this.SendPropertyChanging();
					this._VendPhone = value;
					this.SendPropertyChanged("VendPhone");
					this.OnVendPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendFax", DbType="VarChar(50)")]
		public string VendFax
		{
			get
			{
				return this._VendFax;
			}
			set
			{
				if ((this._VendFax != value))
				{
					this.OnVendFaxChanging(value);
					this.SendPropertyChanging();
					this._VendFax = value;
					this.SendPropertyChanged("VendFax");
					this.OnVendFaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendAcct", DbType="VarChar(50)")]
		public string VendAcct
		{
			get
			{
				return this._VendAcct;
			}
			set
			{
				if ((this._VendAcct != value))
				{
					this.OnVendAcctChanging(value);
					this.SendPropertyChanging();
					this._VendAcct = value;
					this.SendPropertyChanged("VendAcct");
					this.OnVendAcctChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendContact", DbType="VarChar(50)")]
		public string VendContact
		{
			get
			{
				return this._VendContact;
			}
			set
			{
				if ((this._VendContact != value))
				{
					this.OnVendContactChanging(value);
					this.SendPropertyChanging();
					this._VendContact = value;
					this.SendPropertyChanged("VendContact");
					this.OnVendContactChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendCntInactive", DbType="Bit")]
		public System.Nullable<bool> VendCntInactive
		{
			get
			{
				return this._VendCntInactive;
			}
			set
			{
				if ((this._VendCntInactive != value))
				{
					this.OnVendCntInactiveChanging(value);
					this.SendPropertyChanging();
					this._VendCntInactive = value;
					this.SendPropertyChanged("VendCntInactive");
					this.OnVendCntInactiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendorRating", DbType="VarChar(20)")]
		public string VendorRating
		{
			get
			{
				return this._VendorRating;
			}
			set
			{
				if ((this._VendorRating != value))
				{
					this.OnVendorRatingChanging(value);
					this.SendPropertyChanging();
					this._VendorRating = value;
					this.SendPropertyChanged("VendorRating");
					this.OnVendorRatingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompName", DbType="VarChar(120)")]
		public string CompName
		{
			get
			{
				return this._CompName;
			}
			set
			{
				if ((this._CompName != value))
				{
					this.OnCompNameChanging(value);
					this.SendPropertyChanging();
					this._CompName = value;
					this.SendPropertyChanged("CompName");
					this.OnCompNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompAddress1", DbType="VarChar(120)")]
		public string CompAddress1
		{
			get
			{
				return this._CompAddress1;
			}
			set
			{
				if ((this._CompAddress1 != value))
				{
					this.OnCompAddress1Changing(value);
					this.SendPropertyChanging();
					this._CompAddress1 = value;
					this.SendPropertyChanged("CompAddress1");
					this.OnCompAddress1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompAddress2", DbType="VarChar(120)")]
		public string CompAddress2
		{
			get
			{
				return this._CompAddress2;
			}
			set
			{
				if ((this._CompAddress2 != value))
				{
					this.OnCompAddress2Changing(value);
					this.SendPropertyChanging();
					this._CompAddress2 = value;
					this.SendPropertyChanged("CompAddress2");
					this.OnCompAddress2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompAddress3", DbType="VarChar(120)")]
		public string CompAddress3
		{
			get
			{
				return this._CompAddress3;
			}
			set
			{
				if ((this._CompAddress3 != value))
				{
					this.OnCompAddress3Changing(value);
					this.SendPropertyChanging();
					this._CompAddress3 = value;
					this.SendPropertyChanged("CompAddress3");
					this.OnCompAddress3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompCity", DbType="VarChar(100)")]
		public string CompCity
		{
			get
			{
				return this._CompCity;
			}
			set
			{
				if ((this._CompCity != value))
				{
					this.OnCompCityChanging(value);
					this.SendPropertyChanging();
					this._CompCity = value;
					this.SendPropertyChanged("CompCity");
					this.OnCompCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompState", DbType="VarChar(32)")]
		public string CompState
		{
			get
			{
				return this._CompState;
			}
			set
			{
				if ((this._CompState != value))
				{
					this.OnCompStateChanging(value);
					this.SendPropertyChanging();
					this._CompState = value;
					this.SendPropertyChanged("CompState");
					this.OnCompStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompZip", DbType="VarChar(16)")]
		public string CompZip
		{
			get
			{
				return this._CompZip;
			}
			set
			{
				if ((this._CompZip != value))
				{
					this.OnCompZipChanging(value);
					this.SendPropertyChanging();
					this._CompZip = value;
					this.SendPropertyChanged("CompZip");
					this.OnCompZipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompCountry", DbType="VarChar(20)")]
		public string CompCountry
		{
			get
			{
				return this._CompCountry;
			}
			set
			{
				if ((this._CompCountry != value))
				{
					this.OnCompCountryChanging(value);
					this.SendPropertyChanging();
					this._CompCountry = value;
					this.SendPropertyChanged("CompCountry");
					this.OnCompCountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompPhone", DbType="VarChar(50)")]
		public string CompPhone
		{
			get
			{
				return this._CompPhone;
			}
			set
			{
				if ((this._CompPhone != value))
				{
					this.OnCompPhoneChanging(value);
					this.SendPropertyChanging();
					this._CompPhone = value;
					this.SendPropertyChanged("CompPhone");
					this.OnCompPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompFax", DbType="VarChar(50)")]
		public string CompFax
		{
			get
			{
				return this._CompFax;
			}
			set
			{
				if ((this._CompFax != value))
				{
					this.OnCompFaxChanging(value);
					this.SendPropertyChanging();
					this._CompFax = value;
					this.SendPropertyChanged("CompFax");
					this.OnCompFaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShowSalesTax", DbType="Bit")]
		public System.Nullable<bool> ShowSalesTax
		{
			get
			{
				return this._ShowSalesTax;
			}
			set
			{
				if ((this._ShowSalesTax != value))
				{
					this.OnShowSalesTaxChanging(value);
					this.SendPropertyChanging();
					this._ShowSalesTax = value;
					this.SendPropertyChanged("ShowSalesTax");
					this.OnShowSalesTaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalesTaxPercentageRate", DbType="Decimal(18,4)")]
		public System.Nullable<decimal> SalesTaxPercentageRate
		{
			get
			{
				return this._SalesTaxPercentageRate;
			}
			set
			{
				if ((this._SalesTaxPercentageRate != value))
				{
					this.OnSalesTaxPercentageRateChanging(value);
					this.SendPropertyChanging();
					this._SalesTaxPercentageRate = value;
					this.SendPropertyChanged("SalesTaxPercentageRate");
					this.OnSalesTaxPercentageRateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxVerbage", DbType="VarChar(10)")]
		public string TaxVerbage
		{
			get
			{
				return this._TaxVerbage;
			}
			set
			{
				if ((this._TaxVerbage != value))
				{
					this.OnTaxVerbageChanging(value);
					this.SendPropertyChanging();
					this._TaxVerbage = value;
					this.SendPropertyChanged("TaxVerbage");
					this.OnTaxVerbageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UseUSADateFormat", DbType="Bit")]
		public System.Nullable<bool> UseUSADateFormat
		{
			get
			{
				return this._UseUSADateFormat;
			}
			set
			{
				if ((this._UseUSADateFormat != value))
				{
					this.OnUseUSADateFormatChanging(value);
					this.SendPropertyChanging();
					this._UseUSADateFormat = value;
					this.SendPropertyChanged("UseUSADateFormat");
					this.OnUseUSADateFormatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplayPoOrderDateText", DbType="VarChar(10)")]
		public string DisplayPoOrderDateText
		{
			get
			{
				return this._DisplayPoOrderDateText;
			}
			set
			{
				if ((this._DisplayPoOrderDateText != value))
				{
					this.OnDisplayPoOrderDateTextChanging(value);
					this.SendPropertyChanging();
					this._DisplayPoOrderDateText = value;
					this.SendPropertyChanged("DisplayPoOrderDateText");
					this.OnDisplayPoOrderDateTextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplayPoNumber", DbType="VarChar(25)")]
		public string DisplayPoNumber
		{
			get
			{
				return this._DisplayPoNumber;
			}
			set
			{
				if ((this._DisplayPoNumber != value))
				{
					this.OnDisplayPoNumberChanging(value);
					this.SendPropertyChanging();
					this._DisplayPoNumber = value;
					this.SendPropertyChanged("DisplayPoNumber");
					this.OnDisplayPoNumberChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.POLine")]
	public partial class POLine : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _PoHeader;
		
		private short _PoLine1;
		
		private System.Nullable<int> _PoRelNum;
		
		private System.Nullable<short> _RowNum;
		
		private string _PartNumber;
		
		private string _RevisionNum;
		
		private string _LineDesc;
		
		private string _Manufacturer;
		
		private string _VenPartNum;
		
		private string _CommentText;
		
		private System.Nullable<System.DateTime> _DueDate;
		
		private System.Nullable<decimal> _Qty;
		
		private System.Nullable<decimal> _UnitCost;
		
		private string _CostPerCode;
		
		private string _IUM;
		
		private string _JobNum;
		
		private System.Nullable<int> _AssemblySeq;
		
		private System.Nullable<int> _JobSeq;
		
		private string _TranType;
		
		private string _ClassID;
		
		private string _GLAccount;
		
		private string _DispManVenPartNbr;
		
		private string _DispPartNumber;
		
		private string _DispLineDescrip;
		
		private string _DispJobAssy;
		
		private string _DispDueDateText;
		
		private string _DispQty;
		
		private string _DispUnitCost;
		
		private string _DispExtCost;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPoHeaderChanging(long value);
    partial void OnPoHeaderChanged();
    partial void OnPoLine1Changing(short value);
    partial void OnPoLine1Changed();
    partial void OnPoRelNumChanging(System.Nullable<int> value);
    partial void OnPoRelNumChanged();
    partial void OnRowNumChanging(System.Nullable<short> value);
    partial void OnRowNumChanged();
    partial void OnPartNumberChanging(string value);
    partial void OnPartNumberChanged();
    partial void OnRevisionNumChanging(string value);
    partial void OnRevisionNumChanged();
    partial void OnLineDescChanging(string value);
    partial void OnLineDescChanged();
    partial void OnManufacturerChanging(string value);
    partial void OnManufacturerChanged();
    partial void OnVenPartNumChanging(string value);
    partial void OnVenPartNumChanged();
    partial void OnCommentTextChanging(string value);
    partial void OnCommentTextChanged();
    partial void OnDueDateChanging(System.Nullable<System.DateTime> value);
    partial void OnDueDateChanged();
    partial void OnQtyChanging(System.Nullable<decimal> value);
    partial void OnQtyChanged();
    partial void OnUnitCostChanging(System.Nullable<decimal> value);
    partial void OnUnitCostChanged();
    partial void OnCostPerCodeChanging(string value);
    partial void OnCostPerCodeChanged();
    partial void OnIUMChanging(string value);
    partial void OnIUMChanged();
    partial void OnJobNumChanging(string value);
    partial void OnJobNumChanged();
    partial void OnAssemblySeqChanging(System.Nullable<int> value);
    partial void OnAssemblySeqChanged();
    partial void OnJobSeqChanging(System.Nullable<int> value);
    partial void OnJobSeqChanged();
    partial void OnTranTypeChanging(string value);
    partial void OnTranTypeChanged();
    partial void OnClassIDChanging(string value);
    partial void OnClassIDChanged();
    partial void OnGLAccountChanging(string value);
    partial void OnGLAccountChanged();
    partial void OnDispManVenPartNbrChanging(string value);
    partial void OnDispManVenPartNbrChanged();
    partial void OnDispPartNumberChanging(string value);
    partial void OnDispPartNumberChanged();
    partial void OnDispLineDescripChanging(string value);
    partial void OnDispLineDescripChanged();
    partial void OnDispJobAssyChanging(string value);
    partial void OnDispJobAssyChanged();
    partial void OnDispDueDateTextChanging(string value);
    partial void OnDispDueDateTextChanged();
    partial void OnDispQtyChanging(string value);
    partial void OnDispQtyChanged();
    partial void OnDispUnitCostChanging(string value);
    partial void OnDispUnitCostChanged();
    partial void OnDispExtCostChanging(string value);
    partial void OnDispExtCostChanged();
    #endregion
		
		public POLine()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PoHeader", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long PoHeader
		{
			get
			{
				return this._PoHeader;
			}
			set
			{
				if ((this._PoHeader != value))
				{
					this.OnPoHeaderChanging(value);
					this.SendPropertyChanging();
					this._PoHeader = value;
					this.SendPropertyChanged("PoHeader");
					this.OnPoHeaderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="PoLine", Storage="_PoLine1", DbType="SmallInt NOT NULL", IsPrimaryKey=true)]
		public short PoLine1
		{
			get
			{
				return this._PoLine1;
			}
			set
			{
				if ((this._PoLine1 != value))
				{
					this.OnPoLine1Changing(value);
					this.SendPropertyChanging();
					this._PoLine1 = value;
					this.SendPropertyChanged("PoLine1");
					this.OnPoLine1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PoRelNum", DbType="Int")]
		public System.Nullable<int> PoRelNum
		{
			get
			{
				return this._PoRelNum;
			}
			set
			{
				if ((this._PoRelNum != value))
				{
					this.OnPoRelNumChanging(value);
					this.SendPropertyChanging();
					this._PoRelNum = value;
					this.SendPropertyChanged("PoRelNum");
					this.OnPoRelNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RowNum", DbType="SmallInt")]
		public System.Nullable<short> RowNum
		{
			get
			{
				return this._RowNum;
			}
			set
			{
				if ((this._RowNum != value))
				{
					this.OnRowNumChanging(value);
					this.SendPropertyChanging();
					this._RowNum = value;
					this.SendPropertyChanged("RowNum");
					this.OnRowNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PartNumber", DbType="VarChar(50)")]
		public string PartNumber
		{
			get
			{
				return this._PartNumber;
			}
			set
			{
				if ((this._PartNumber != value))
				{
					this.OnPartNumberChanging(value);
					this.SendPropertyChanging();
					this._PartNumber = value;
					this.SendPropertyChanged("PartNumber");
					this.OnPartNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RevisionNum", DbType="VarChar(120)")]
		public string RevisionNum
		{
			get
			{
				return this._RevisionNum;
			}
			set
			{
				if ((this._RevisionNum != value))
				{
					this.OnRevisionNumChanging(value);
					this.SendPropertyChanging();
					this._RevisionNum = value;
					this.SendPropertyChanged("RevisionNum");
					this.OnRevisionNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LineDesc", DbType="VarChar(400)")]
		public string LineDesc
		{
			get
			{
				return this._LineDesc;
			}
			set
			{
				if ((this._LineDesc != value))
				{
					this.OnLineDescChanging(value);
					this.SendPropertyChanging();
					this._LineDesc = value;
					this.SendPropertyChanged("LineDesc");
					this.OnLineDescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Manufacturer", DbType="VarChar(50)")]
		public string Manufacturer
		{
			get
			{
				return this._Manufacturer;
			}
			set
			{
				if ((this._Manufacturer != value))
				{
					this.OnManufacturerChanging(value);
					this.SendPropertyChanging();
					this._Manufacturer = value;
					this.SendPropertyChanged("Manufacturer");
					this.OnManufacturerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VenPartNum", DbType="VarChar(50)")]
		public string VenPartNum
		{
			get
			{
				return this._VenPartNum;
			}
			set
			{
				if ((this._VenPartNum != value))
				{
					this.OnVenPartNumChanging(value);
					this.SendPropertyChanging();
					this._VenPartNum = value;
					this.SendPropertyChanged("VenPartNum");
					this.OnVenPartNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommentText", DbType="VarChar(240)")]
		public string CommentText
		{
			get
			{
				return this._CommentText;
			}
			set
			{
				if ((this._CommentText != value))
				{
					this.OnCommentTextChanging(value);
					this.SendPropertyChanging();
					this._CommentText = value;
					this.SendPropertyChanged("CommentText");
					this.OnCommentTextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DueDate", DbType="Date")]
		public System.Nullable<System.DateTime> DueDate
		{
			get
			{
				return this._DueDate;
			}
			set
			{
				if ((this._DueDate != value))
				{
					this.OnDueDateChanging(value);
					this.SendPropertyChanging();
					this._DueDate = value;
					this.SendPropertyChanged("DueDate");
					this.OnDueDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Qty", DbType="Decimal(18,4)")]
		public System.Nullable<decimal> Qty
		{
			get
			{
				return this._Qty;
			}
			set
			{
				if ((this._Qty != value))
				{
					this.OnQtyChanging(value);
					this.SendPropertyChanging();
					this._Qty = value;
					this.SendPropertyChanged("Qty");
					this.OnQtyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitCost", DbType="Decimal(18,4)")]
		public System.Nullable<decimal> UnitCost
		{
			get
			{
				return this._UnitCost;
			}
			set
			{
				if ((this._UnitCost != value))
				{
					this.OnUnitCostChanging(value);
					this.SendPropertyChanging();
					this._UnitCost = value;
					this.SendPropertyChanged("UnitCost");
					this.OnUnitCostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CostPerCode", DbType="VarChar(8)")]
		public string CostPerCode
		{
			get
			{
				return this._CostPerCode;
			}
			set
			{
				if ((this._CostPerCode != value))
				{
					this.OnCostPerCodeChanging(value);
					this.SendPropertyChanging();
					this._CostPerCode = value;
					this.SendPropertyChanged("CostPerCode");
					this.OnCostPerCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IUM", DbType="VarChar(10)")]
		public string IUM
		{
			get
			{
				return this._IUM;
			}
			set
			{
				if ((this._IUM != value))
				{
					this.OnIUMChanging(value);
					this.SendPropertyChanging();
					this._IUM = value;
					this.SendPropertyChanged("IUM");
					this.OnIUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobNum", DbType="VarChar(20)")]
		public string JobNum
		{
			get
			{
				return this._JobNum;
			}
			set
			{
				if ((this._JobNum != value))
				{
					this.OnJobNumChanging(value);
					this.SendPropertyChanging();
					this._JobNum = value;
					this.SendPropertyChanged("JobNum");
					this.OnJobNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AssemblySeq", DbType="Int")]
		public System.Nullable<int> AssemblySeq
		{
			get
			{
				return this._AssemblySeq;
			}
			set
			{
				if ((this._AssemblySeq != value))
				{
					this.OnAssemblySeqChanging(value);
					this.SendPropertyChanging();
					this._AssemblySeq = value;
					this.SendPropertyChanged("AssemblySeq");
					this.OnAssemblySeqChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobSeq", DbType="Int")]
		public System.Nullable<int> JobSeq
		{
			get
			{
				return this._JobSeq;
			}
			set
			{
				if ((this._JobSeq != value))
				{
					this.OnJobSeqChanging(value);
					this.SendPropertyChanging();
					this._JobSeq = value;
					this.SendPropertyChanged("JobSeq");
					this.OnJobSeqChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TranType", DbType="VarChar(10)")]
		public string TranType
		{
			get
			{
				return this._TranType;
			}
			set
			{
				if ((this._TranType != value))
				{
					this.OnTranTypeChanging(value);
					this.SendPropertyChanging();
					this._TranType = value;
					this.SendPropertyChanged("TranType");
					this.OnTranTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClassID", DbType="VarChar(40)")]
		public string ClassID
		{
			get
			{
				return this._ClassID;
			}
			set
			{
				if ((this._ClassID != value))
				{
					this.OnClassIDChanging(value);
					this.SendPropertyChanging();
					this._ClassID = value;
					this.SendPropertyChanged("ClassID");
					this.OnClassIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GLAccount", DbType="VarChar(40)")]
		public string GLAccount
		{
			get
			{
				return this._GLAccount;
			}
			set
			{
				if ((this._GLAccount != value))
				{
					this.OnGLAccountChanging(value);
					this.SendPropertyChanging();
					this._GLAccount = value;
					this.SendPropertyChanged("GLAccount");
					this.OnGLAccountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DispManVenPartNbr", DbType="VarChar(50)")]
		public string DispManVenPartNbr
		{
			get
			{
				return this._DispManVenPartNbr;
			}
			set
			{
				if ((this._DispManVenPartNbr != value))
				{
					this.OnDispManVenPartNbrChanging(value);
					this.SendPropertyChanging();
					this._DispManVenPartNbr = value;
					this.SendPropertyChanged("DispManVenPartNbr");
					this.OnDispManVenPartNbrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DispPartNumber", DbType="VarChar(120)")]
		public string DispPartNumber
		{
			get
			{
				return this._DispPartNumber;
			}
			set
			{
				if ((this._DispPartNumber != value))
				{
					this.OnDispPartNumberChanging(value);
					this.SendPropertyChanging();
					this._DispPartNumber = value;
					this.SendPropertyChanged("DispPartNumber");
					this.OnDispPartNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DispLineDescrip", DbType="VarChar(510)")]
		public string DispLineDescrip
		{
			get
			{
				return this._DispLineDescrip;
			}
			set
			{
				if ((this._DispLineDescrip != value))
				{
					this.OnDispLineDescripChanging(value);
					this.SendPropertyChanging();
					this._DispLineDescrip = value;
					this.SendPropertyChanged("DispLineDescrip");
					this.OnDispLineDescripChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DispJobAssy", DbType="VarChar(20)")]
		public string DispJobAssy
		{
			get
			{
				return this._DispJobAssy;
			}
			set
			{
				if ((this._DispJobAssy != value))
				{
					this.OnDispJobAssyChanging(value);
					this.SendPropertyChanging();
					this._DispJobAssy = value;
					this.SendPropertyChanged("DispJobAssy");
					this.OnDispJobAssyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DispDueDateText", DbType="VarChar(20)")]
		public string DispDueDateText
		{
			get
			{
				return this._DispDueDateText;
			}
			set
			{
				if ((this._DispDueDateText != value))
				{
					this.OnDispDueDateTextChanging(value);
					this.SendPropertyChanging();
					this._DispDueDateText = value;
					this.SendPropertyChanged("DispDueDateText");
					this.OnDispDueDateTextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DispQty", DbType="VarChar(20)")]
		public string DispQty
		{
			get
			{
				return this._DispQty;
			}
			set
			{
				if ((this._DispQty != value))
				{
					this.OnDispQtyChanging(value);
					this.SendPropertyChanging();
					this._DispQty = value;
					this.SendPropertyChanged("DispQty");
					this.OnDispQtyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DispUnitCost", DbType="VarChar(20)")]
		public string DispUnitCost
		{
			get
			{
				return this._DispUnitCost;
			}
			set
			{
				if ((this._DispUnitCost != value))
				{
					this.OnDispUnitCostChanging(value);
					this.SendPropertyChanging();
					this._DispUnitCost = value;
					this.SendPropertyChanged("DispUnitCost");
					this.OnDispUnitCostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DispExtCost", DbType="VarChar(20)")]
		public string DispExtCost
		{
			get
			{
				return this._DispExtCost;
			}
			set
			{
				if ((this._DispExtCost != value))
				{
					this.OnDispExtCostChanging(value);
					this.SendPropertyChanging();
					this._DispExtCost = value;
					this.SendPropertyChanged("DispExtCost");
					this.OnDispExtCostChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.employee")]
	public partial class employee
	{
		
		private int _id;
		
		private string _fName;
		
		private string _lName;
		
		private System.Nullable<int> _positionId;
		
		private System.Nullable<System.DateTime> _birthday;
		
		private System.Nullable<System.DateTime> _startDate;
		
		private System.Nullable<System.DateTime> _endDate;
		
		private System.Nullable<int> _classificationId;
		
		private string _location;
		
		public employee()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fName", DbType="VarChar(24)")]
		public string fName
		{
			get
			{
				return this._fName;
			}
			set
			{
				if ((this._fName != value))
				{
					this._fName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lName", DbType="VarChar(24)")]
		public string lName
		{
			get
			{
				return this._lName;
			}
			set
			{
				if ((this._lName != value))
				{
					this._lName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_positionId", DbType="Int")]
		public System.Nullable<int> positionId
		{
			get
			{
				return this._positionId;
			}
			set
			{
				if ((this._positionId != value))
				{
					this._positionId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birthday", DbType="DateTime")]
		public System.Nullable<System.DateTime> birthday
		{
			get
			{
				return this._birthday;
			}
			set
			{
				if ((this._birthday != value))
				{
					this._birthday = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_startDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> startDate
		{
			get
			{
				return this._startDate;
			}
			set
			{
				if ((this._startDate != value))
				{
					this._startDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_endDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> endDate
		{
			get
			{
				return this._endDate;
			}
			set
			{
				if ((this._endDate != value))
				{
					this._endDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_classificationId", DbType="Int")]
		public System.Nullable<int> classificationId
		{
			get
			{
				return this._classificationId;
			}
			set
			{
				if ((this._classificationId != value))
				{
					this._classificationId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_location", DbType="Char(24)")]
		public string location
		{
			get
			{
				return this._location;
			}
			set
			{
				if ((this._location != value))
				{
					this._location = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
